version: "3.9"

networks:
  app-net:
    driver: bridge

volumes:
  mongo_data:

services:

  mongo:
    image: mongo:6
    container_name: carbecho-db
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net

  api:
    build: ./server
    container_name: carbecho-api
    env_file:
      - /opt/carbecho-secrets/server.env
    depends_on:
      - mongo
    networks:
      - app-net

  client:
    build: ./client
    container_name: carbecho-client
    depends_on:
      - api
    networks:
      - app-net

  nginx:
    image: nginx
    container_name: carbecho-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - api
    networks:
      - app-net